config/routes.rb
Rails.application.routes.draw do

  root to: 'sessions#index'

  resources :complainants
  resources :crimes
  resources :dashboard, only: [:index]


  get '/', to: 'sessions#index'
  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  post '/users/:id/toggle_role', to: 'users#toggle_role', as: 'toggle_user_role'
  post '/users/:id/toggle_status', to: 'users#toggle_status', as: 'toggle_user_status'
  delete '/users/:id', to: 'users#destroy', as: 'destroy_user'

  resources :first_information_reports
  post '/first_information_reports/:id/approve', to: 'first_information_reports#approve', as: 'approve_fir'
  post '/first_information_reports/:id/reject', to: 'first_information_reports#reject', as: 'reject_fir'

  resources :categories
  post 'categories/:id/activate', to: 'categories#activate', as: 'activate_category'

  get 'search/index', to: 'search#index', as: 'search'
  post 'search/index', to: 'search#index', as: 'find'

  get 'reports/index', to: 'reports#index', as: 'get_report_form'
  post 'reports/index', to: 'reports#index', as: 'post_report_form'

  get '*path' => redirect('/')
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user
  def index
    @officers = User.where(admin: false).all.count
    @complainants = Complainant.all.count

    p_firs = FirstInformationReport.where(status: 0)
    @pending_firs = p_firs.nil? ? 0 : p_firs.all

    @firs = FirstInformationReport.all.order(created_at: :desc).limit(10)

    @crimes = Crime.includes(%i[categories user]).all.order(created_at: :desc).limit(7)
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
  def all_firs(firs)
    content_tag :tbody do
      firs.each_with_index do |fir, _index|
        concat(content_tag(:tr) do
          concat(content_tag(:td, fir.offense))
          concat(content_tag(:td, format_time(fir.date, :long, 'N/A')))
          concat(content_tag(:td, class: 'status-col') do
            content_tag(:span, '', class: "status #{fir.status}") + fir.status
          end)
          if current_user.admin?
            concat(content_tag(:td,
                               link_to(update_message(fir.status), get_link_type(fir),
                                       method: :post, class: "btn btn-#{update_link_class(fir.status)} d-block")))
          else
            concat(content_tag(:td, 'N/A', class: 'd-block'))
          end
        end)
      end
    end
  end

  def update_message(status)
    status.eql?('approved') ? 'Reject' : 'Approve'
  end

  def get_link_type(fir)
    update_message(fir.status).eql?('Approve') ? approve_fir_path(fir) : reject_fir_path(fir)
  end

  def update_link_class(status)
    status.eql?('approved') ? 'danger' : 'success'
  end

  def all_crimes(crimes)
    content_tag(:div) do
      crimes.each_with_index do |crime, _index|
        concat(content_tag(:div, class: 'customers__card-body') do
          concat(content_tag(:div, class: 'customer') do
            concat(content_tag(:div, class: 'info') do
              concat(image_tag(asset_path('npf.png'), width: '30px', height: '30px', alt: 'icon'))
              concat(content_tag(:div) do
                concat(content_tag(:h4, crime.statements.to_s))
                concat(
                  content_tag(
                    :small,
                    "#{crime.accuser} (#{format_time(crime.created_at, :short, 'N/A')})"
                  )
                )
              end)
            end)
            concat(content_tag(:div, class: 'contact') do
              concat(link_to('view', crime, class: 'btn btn-dark'))
            end)
          end)
        end)
      end
    end
  end
end

app/views/dashboard/_header.html.erb
<header>
  <h3>
    <label for="nav-toggle">
      <span class="las la-bars hamburger"></span>
      <% if defined?(title) && title %>
        <%= title %>
      <% else %>
        CRMS
      <% end %>
    </label>
  </h3>
  <div class="user-wrapper">
    <img src="<%= current_user.avatar.thumbnail %>" alt="user-icon" srcset="">
    <div class="">
      <h5><%= current_user.firstname %></h5>
      <small><%= current_user.admin ? 'Admin' : 'Police' %></small>
      <small class="text-sm-end"><%= link_to 'Logout', logout_path, method: :delete  %></small>
    </div>
  </div>
</header>

app/views/dashboard/_sidebar.html.erb
<input type="checkbox" id="nav-toggle">
<div class="sidebar">
  <div class="sidebar__brand">
    <h2><span class="lab la-accusoft"></span><span class="bar-text">CRIME INFO SYS.</span></h2>
  </div>

  <div class="sidebar__menu">
    <ul>
      <li class="menu-list">
        <%= link_to dashboard_index_path, class: "#{active_action?'dashboard'}" do %>
          <span class="las la-igloo"></span>
          <span class="bar-text">Dashboard</span>
        <% end %>
      </li>
      <li class="menu-list">
        <%= link_to user_path(current_user), class: '' do %>
          <span class="las la-user-circle"></span>
          </span><span class="bar-text">Profile</span>
        <% end %>
      </li>
      <% if current_user.admin %>
        <li class="menu-list">
          <%= link_to users_path, class:  "#{active_action?'users'}" do %>
            <span class="las la-users"></span>
            <span class="bar-text">Users Management</span>
          <% end %>
        </li>
        <% end %>
      <li class="menu-list">
        <%= link_to first_information_reports_path, class: "#{active_action?'first_information_reports'}" do %>
          <span class="las la-clipboard-list"></span>
          <span class="bar-text">First Information Reports</span>
        <% end %>
      </li>
      <li class="menu-list">
        <%= link_to categories_path, class: "#{active_action?'categories'}" do %>
          <span class="las la-columns"></span>
          <span class="bar-text">Crime Categories</span>
        <% end %>
      </li>
      <li class="menu-list">
        <%= link_to crimes_path, class: "#{active_action?'crimes'}" do %>
          <span class="las la-assistive-listening-systems"></span>
          <span class="bar-text">Crimes</span>
        <% end %>
      </li>
      <li class="menu-list">
        <%= link_to complainants_path, class: "#{active_action?'complainants'}" do %>
          <span class="las la-user-friends"></span>
          <span class="bar-text">Complainants</span>
        <% end %>
      </li>
      <li class="menu-list">
        <%= link_to search_path, class: "#{active_action?'search'}" do %>
          <span class="las la-search"></span>
          <span class="bar-text">Search</span>
        <% end %>
      </li>
      <li class="menu-list">
        <%= link_to get_report_form_path, class: "#{active_action?'reports'}"  do %>
          <span class="las la-clipboard-list"></span>
          <span class="bar-text">Generate Reports</span>
        <% end %>
        <a href="#"></a>
      </li>
      <li class="menu-list">
        <%= link_to logout_path, method: :delete do %>
          <span class="las la-long-arrow-alt-left"></span><span class="bar-text">Logout</span>
        <% end %>
      </li>
    </ul>
  </div>
</div>

app/views/dashboard/index.html.erb
<%= render 'sidebar' %>
<div class="main-content">
  <%= render 'header', title: 'Dashboard' %>
  <main>
    <%= render 'layouts/alerts' %>
    <div class="cards">
      <div class="cards__single">
        <div class="">
          <h1><%= @officers %></h1>
          <span class="metacard">Police Officers</span>
        </div>
        <div class="">
          <span class="la la-users icon"></span>
        </div>
      </div>
      <div class="cards__single">
        <div class="">
          <h1><%= @crimes.count %></h1>
          <span class="metacard">Reported Crimes</span>
        </div>
        <div class="">
          <span class="la la-users icon"></span>
        </div>
      </div>
      <div class="cards__single">
        <div class="">
          <h1><%= @complainants %></h1>
          <span class="metacard">Complainants</span>
        </div>
        <div class="">
          <span class="la la-clipboard-list icon"></span>
        </div>
      </div>
      <div class="cards__single">
        <div class="">
          <h1><%= @firs.count %></h1>
          <span class="metacard">Received FIRs</span>
        </div>
        <div class="">
          <span class="la la-clipboard-list icon"></span>
        </div>
      </div>
    </div>
    <section class="recent-grid">
      <div class="projects">
        <div class="projects__card b-none">
          <div class="projects__card-header">
            <h4>Latest FIRs  (<%= @pending_firs.count %> pending)</h4>
            <%= link_to first_information_reports_path do %>
              <button>See all <span class="las la-arrow-right"></span></button>
            <% end %>
          </div>
          <div class="projects__card-body">
            <div class="table-responsive">
              <table width="100%">
                <thead>
                  <tr>
                    <td>Offence</td>
                    <td>Date</td>
                    <td>Status</td>
                    <td>Action</td>
                  </tr>
                </thead>
                <tbody>
                  <%= all_firs(@firs) %>
                </tbody>
              </table>
            </div>

          </div>
        </div>
      </div>
      <div class="customers">
        <div class="customers__card">
          <div class="customers__card-header">
            <h4>Latest Crimes </h4>
            <%= link_to crimes_path do %>
              <button>See all <span class="las la-arrow-right"></span></button>
            <% end %>
          </div>
          <%= all_crimes(@crimes) %>
        </div>
      </div>
    </section>
  </main>
  <div class="text-center">
    <%= render 'layouts/footer' %>
  </div>
</div>

app/views/dashboard/not_found.html.erb
<%= render './dashboard/sidebar' %>
<div class="main-content">
  <%= render './dashboard/header', title: 'User Profile' %>
  <main>
    <%= render 'layouts/alerts' %>
    <div class="bg-white m-2 p-4 text-center text-danger">
      <p>Resource not found!</p>
    </div>
  </main>
  <div class="text-center">
    <%= render 'layouts/footer' %>
  </div>
</div>