config/routes.rb
Rails.application.routes.draw do

  root to: 'sessions#index'

  resources :complainants
  resources :crimes
  resources :dashboard, only: [:index]


  get '/', to: 'sessions#index'
  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  post '/users/:id/toggle_role', to: 'users#toggle_role', as: 'toggle_user_role'
  post '/users/:id/toggle_status', to: 'users#toggle_status', as: 'toggle_user_status'
  delete '/users/:id', to: 'users#destroy', as: 'destroy_user'

  resources :first_information_reports
  post '/first_information_reports/:id/approve', to: 'first_information_reports#approve', as: 'approve_fir'
  post '/first_information_reports/:id/reject', to: 'first_information_reports#reject', as: 'reject_fir'

  resources :categories
  post 'categories/:id/activate', to: 'categories#activate', as: 'activate_category'

  get 'search/index', to: 'search#index', as: 'search'
  post 'search/index', to: 'search#index', as: 'find'

  get 'reports/index', to: 'reports#index', as: 'get_report_form'
  post 'reports/index', to: 'reports#index', as: 'post_report_form'

  get '*path' => redirect('/')
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  mount_uploader :avatar, AvatarUploader

  validates :email, presence: true, length: { maximum: 255 }, uniqueness: { case_sensitive: false },
                    format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :firstname, :lastname, :gender, :phone, :address, presence: true
  has_many :crimes, class_name: 'Crime', dependent: :destroy
  has_many :categories, class_name: 'Category', dependent: :destroy
  has_many :complainants, class_name: 'Complainant', dependent: :destroy
  has_many :first_information_reports, class_name: 'FirstInformationReport', dependent: :destroy

  def username
    email.split('@')[0].capitalize
  end

  def full_name
    "#{firstname} #{lastname}"
  end

  def account_type
    admin ? 'Admin Officer' : 'Police Officer'
  end

  scope :all_active, -> { where(active: TRUE).all }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, only: %i[show index edit update destroy]
  before_action :authenticate_admin, except: %i[edit show update]
  before_action :now_user, only: %i[edit show toggle_role toggle_status]

  def index
    @users = User.paginate(page: params[:page], per_page: 15).order('id ASC')
  end

  def new
    @user = User.new
  end

  def edit
    return if now_user.eql?(current_user) || current_user.admin?

    render :'dashboard/not_found' if @user.nil?
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: 'User profile updated successfully'
    else
      flash[:notice] = 'Profile update NOT successful'
      render :edit
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path, notice: "User created successfully. Unique ID: #{@user.id}"
    else
      render :new, notice: 'Something went wrong. Please try again.'
    end
  end

  def show
    render :'dashboard/not_found' if @user.nil?
    return if now_user.eql?(current_user) || current_user.admin?

    flash[:notice] = 'You are not an admin!'
    redirect_back(fallback_location: users_path)
  end

  def destroy; end

  def toggle_role
    @user.admin = @user.admin.eql?(true) ? false : true
    msg = "User with id #{@user.id} role could not be updated."
    msg = "User with id #{@user.id} role updated to #{@user.admin ? 'Admin' : 'Officer'}." if @user.save
    flash[:notice] = msg
    redirect_to users_path
  end

  def toggle_status
    msg = ''
    @user.active = @user.active.eql?(true) ? false : true
    msg = "User with id #{@user.id} is NOW ACTIVE." if @user.active.eql?(true)
    msg = "User with id #{@user.id} is NOW INACTIVE." if @user.active.eql?(false)
    flash[:notice] = @user.save ? msg : 'User status cannot be changed!'
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user)
      .permit(:email, :password, :firstname, :lastname, :gender, :phone, :address, :avatar, :admin, :active)
  end

  def now_user
    @user = User.find_by(id: params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(user, html: {multipart: true}) do |f| %>
  <div class="form-group text-start m-3">
    <div class="row mb-3">
      <div class="col-md-6">
        <%= f.label :firstname %>
        <%= f.text_field :firstname,
                          autofocus: true, required: true, autocomplete: "text", class: "form-control"%>
      </div>

      <div class="col-md-6">
        <%= f.label :lastname %>
        <%= f.text_field :lastname,
                          required: true, autocomplete: "text", class: "form-control"%>
      </div>
    </div>

    <div class="row mb-3">
      <div class="col-md-4">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email,
                          required: true, autocomplete: "text", class: "form-control"%>
      </div>

      <div class="col-md-4">
        <%= f.label :phone, 'Phone Number' %>
        <%= f.number_field :phone,
                          required: true, autocomplete: "number", class: "form-control"%>
      </div>

      <div class="col-md-4">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password,
                           required: true, class: "form-control"%>
      </div>
    </div>

    <div class="form-group mb-3">
      <%= f.label :address, 'Full address' %>
      <%= f.text_field :address,
                        required: true, autocomplete: "text", class: "form-control"%>
    </div>

    <div class="row mb-3">
      <div class="col-md-6">
        <%= f.label :gender, 'Gender' %>
        <select name="user[gender]" class="form-control" required>
          <option value="">Choose...</option>
          <option value="Male">Male</option>
          <option value="Female">Female</option>
        </select>
      </div>

      <div class="col-md-6">
        <%= f.label :admin, 'Check if user is admin', class: 'd-block' %>
        <%= f.check_box :admin %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :avatar, 'Attach profile image:' %>
      <%= f.file_field :avatar, class: 'form-control' %>
    </div>
  </div>
  <div class="mt-4 text-center">
    <%= f.submit class: 'btn btn-primary move-right' %>
  </div>
<% end %>

app/views/users/_nav.html.erb
<div class="d-flex justify-content-between bg-white p-2 mb-2">
  <h4>Menu</h4>
  <nav>
    <%= link_to 'Edit Profile', edit_user_path, class: 'btn btn-warning' %>
  </nav>
</div>

app/views/users/_nav_users.html.erb
<div class="d-flex justify-content-between bg-white p-2 mb-2">
  <h4>Menu</h4>
  <nav>
    <%= link_to 'Add User', new_user_path, class: 'btn btn-success' %>
    <%= link_to 'All Users', users_path, class: 'btn btn-info' %>
  </nav>
</div>

app/views/users/edit.html.erb
<%= render './dashboard/sidebar' %>
<div class="main-content">
  <%= render './dashboard/header', title: 'Edit Profile' %>
  <main>
    <%= render 'layouts/alerts' %>
    <%= render 'layouts/form_errors', obj: @user %>
    <%= render 'nav', user: @user %>
    <div class="bg-white mt-4 px-3 pb-3">
      <%= render 'form', user: @user %>
    </div>
  </main>
  <div class="text-center">
    <%= render 'layouts/footer' %>
  </div>
</div>

app/views/users/index.html.erb
<%= render './dashboard/sidebar' %>
<div class="main-content">
  <%= render './dashboard/header', title: 'All Users' %>
  <main>
    <%= render 'layouts/alerts' %>
    <%= render 'nav_users' %>
    <div class="bg-white p-2 ">
      <table class="table">
        <thead>
        <tr>
          <th scope="col">UID</th>
          <th scope="col">Full Name</th>
          <th scope="col">Email</th>
          <th scope="col">Role</th>
          <th scope="col">Status</th>
          <th scope="col">Actions</th>
        </tr>
        </thead>
        <tbody>
        <% @users.each do |user| %>
          <% next if user.eql?(current_user) %>
          <tr class="mb-3">
            <th scope="row"><%= id_formatter(user.id) %></th>
            <td><%= "#{user.firstname.titlecase} #{user.lastname}" %></td>
            <td><%= user.email %></td>
            <td>
              <%= user.admin ? 'Admin Officer' : 'Police Officer' %>
              <%= link_to toggle_user_role_path(user), method: :post, data: { confirm: 'Change User Role?' } do %>
                <% badge = user.admin ? 'success' : 'warning' %>
                <span class="badge bg-<%= badge %>"><span class="las la-road"></span></span>
              <% end %>
            </td>
            <td>
              <% if user.active %>
                <span class="badge bg-success">Active</span>
                <%= link_to  toggle_user_status_path(user), class: 'badge bg-danger', method: :post, data: { confirm: 'Deactivate user?' } do %>
                  <span class="badge bg-danger"><span class="las la-toggle-off"></span></span>
                <% end %>
              <% else %>
                <span class="badge bg-danger">Inactive</span>
                <%= link_to toggle_user_status_path(user), class: 'badge bg-success', method: :post, data: { confirm: 'Activate user?' } do %>
                  <span class="badge bg-success"><span class="las la-toggle-on"></span></span>
                <% end %>
              <% end %>
            </td>
            <td>
              <%= link_to user_path(user) do %>
                <span class="badge bg-warning"><span class="las la-eye"></span> View</span>
              <% end %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
      <%= will_paginate @users, renderer: BootstrapPagination::Rails %>
    </div>

  </main>
  <div class="text-center">
    <%= render 'layouts/footer' %>
  </div>
</div>

app/views/users/new.html.erb
<%= render './dashboard/sidebar' %>
<div class="main-content">
  <%= render './dashboard/header', title: 'New User' %>
  <main>
    <%= render 'layouts/alerts' %>
    <%= render 'nav_users', user: @user %>
    <div class="bg-white p-2 text-center">
      <h5>User registration page</h5>
      <%= render 'form', user: @user %>
    </div>
  </main>
  <div class="text-center">
    <%= render 'layouts/footer' %>
  </div>
</div>

app/views/users/show.html.erb
<%= render './dashboard/sidebar' %>
<div class="main-content">
  <%= render './dashboard/header', title: 'User Profile' %>
  <main>
    <%= render 'layouts/alerts' %>
    <%= render 'nav', user: @user %>
    <div class="card mb-3">
      <div class="row g-0">
        <div class="col-md-4 d-flex justify-content-center align-items-center">
          <img src="<%= @user.avatar.profile %>" alt="user-image" class="img-thumbnail"/>
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <div class="card">
              <div class="card-header">
                <h2 class="card-title">Profile Details</h2>
              </div>
              <ul class="list-group list-group-flush">
                <li class="list-group-item d-flex justify-content-between">
                  <span>Lastname:</span>
                  <span class="badge bg-primary d-inline-block pt-2"><%= @user.lastname.upcase %></span>
                </li>
                <li class="list-group-item d-flex justify-content-between">
                  <span>Firstname:</span>
                  <span class="badge bg-secondary d-inline-block pt-2"><%= @user.firstname.titlecase %></span>
                </li>
                <li class="list-group-item d-flex justify-content-between">
                  <span>Email:</span>
                  <span class="badge bg-info d-inline-block pt-2"><%= @user.email %></span>
                </li>
                <li class="list-group-item d-flex justify-content-between">
                  <span>Gender:</span>
                  <span class="badge bg-success d-inline-block pt-2"><%= @user.gender %></span>
                </li>
                <li class="list-group-item d-flex justify-content-between">
                  <span>Address:</span>
                  <span class="badge bg-dark d-inline-block pt-2"><%= @user.address %></span>
                </li>
                <li class="list-group-item d-flex justify-content-between">
                  <span>Phone Number:</span>
                  <span class="badge bg-primary d-inline-block pt-2"><%= @user.phone %></span>
                </li>
                <li class="list-group-item d-flex justify-content-between">
                  <span>Account created at:</span>
                  <span class="badge bg-warning d-inline-block pt-2"><%= @user.created_at.to_formatted_s %></span>
                </li>
                <li class="list-group-item d-flex justify-content-between">
                  <span>Last profile update:</span>
                  <span class="badge bg-info d-inline-block pt-2"><%= time_ago_in_words(@user.updated_at) %></span>
                </li>
                <li class="list-group-item d-flex justify-content-between">
                  <span>User Type:</span>
                  <span class="badge bg-success d-inline-block pt-2"><%= @user.admin ? 'Admin Officer' : 'Police Officer' %></span>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
  <div class="text-center">
    <%= render 'layouts/footer' %>
  </div>
</div>