config/routes.rb
Rails.application.routes.draw do

  root to: 'sessions#index'

  resources :complainants
  resources :crimes
  resources :dashboard, only: [:index]


  get '/', to: 'sessions#index'
  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  post '/users/:id/toggle_role', to: 'users#toggle_role', as: 'toggle_user_role'
  post '/users/:id/toggle_status', to: 'users#toggle_status', as: 'toggle_user_status'
  delete '/users/:id', to: 'users#destroy', as: 'destroy_user'

  resources :first_information_reports
  post '/first_information_reports/:id/approve', to: 'first_information_reports#approve', as: 'approve_fir'
  post '/first_information_reports/:id/reject', to: 'first_information_reports#reject', as: 'reject_fir'

  resources :categories
  post 'categories/:id/activate', to: 'categories#activate', as: 'activate_category'

  get 'search/index', to: 'search#index', as: 'search'
  post 'search/index', to: 'search#index', as: 'find'

  get 'reports/index', to: 'reports#index', as: 'get_report_form'
  post 'reports/index', to: 'reports#index', as: 'post_report_form'

  get '*path' => redirect('/')
end

app/models/first_information_report.rb
class FirstInformationReport < ApplicationRecord
  belongs_to :user
  belongs_to :complainant
  validates :offense, :date, :location, :suspect_details, presence: true, length: { minimum: 5 }

  enum status: %i[pending approved rejected]

  scope :all_active, -> { where(active: TRUE).all }
  scope :the_default, -> { where(status: 0).all }
  scope :the_approved, -> { where(status: 1).all }
  scope :the_rejected, -> { where(status: 2).all }
  scope :result, ->(start_date, end_date) { where('date >= ? and date <= ?', start_date, end_date).all }
end

app/controllers/first_information_reports_controller.rb
class FirstInformationReportsController < ApplicationController
  before_action :authenticate_user
  before_action :authenticate_admin, only: %i[destroy approve reject]
  before_action :set_first_information_report, only: %i[show edit update destroy approve reject]

  def index
    @firs = FirstInformationReport
      .where(active: TRUE)
      .includes(%i[user complainant])
      .paginate(page: params[:page], per_page: 10)
      .order('created_at DESC')
  end

  def show
    render :'dashboard/not_found' if @first_information_report.nil?
  end

  def new
    @first_information_report = FirstInformationReport.new
    @users = User.all_active
    @complainants = Complainant.all_active
  end

  def edit
    render :'dashboard/not_found' if @first_information_report.nil?

    @users = User.all_active
    @complainants = Complainant.all_active
  end

  def create
    @first_information_report = FirstInformationReport.new(first_information_report_params)

    respond_to do |format|
      if @first_information_report.save
        format.html do
          redirect_to @first_information_report, notice: 'First information report was successfully created.'
        end
        format.json { render :show, status: :created, location: @first_information_report }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @first_information_report.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @first_information_report.update(first_information_report_params)
        format.html do
          redirect_to @first_information_report, notice: 'First information report was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @first_information_report }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @first_information_report.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @first_information_report.active = false
    @first_information_report.save
    respond_to do |format|
      format.html do
        redirect_to first_information_reports_url,
                    notice: "FIR with ID: #{@first_information_report.id} was successfully deleted."
      end
      format.json { head :no_content }
    end
  end

  def approve
    @first_information_report.approved!
    if @first_information_report.save
      redirect_to first_information_reports_path,
                  notice: "FIR with ID: #{@first_information_report.id} approved successfully!"
    else
      redirect_to first_information_report_path,
                  notice: "FIR with ID: #{@first_information_report.id} approval failed. Please, try again."
    end
  end

  def reject
    @first_information_report.rejected!
    if @first_information_report.save
      redirect_to first_information_reports_path,
                  notice: "FIR with ID: #{@first_information_report.id} rejected successfully!"
    else
      redirect_to first_information_report_path,
                  notice: "FIR with ID: #{@first_information_report.id} rejection failed. Please, try again."
    end
  end

  private

  def set_first_information_report
    @first_information_report = FirstInformationReport.find_by(id: params[:id])
  end

  def first_information_report_params
    params.require(:first_information_report).permit(:user_id, :complainant_id, :offense, :date, :location,
                                                     :suspect_details, :status, :active)
  end
end

app/helpers/first_information_reports_helper.rb
module FirstInformationReportsHelper
  def detect_status(status)
    case status
    when 'pending'
      'warning'
    when 'approved'
      'success'
    else
      'danger'
    end
  end
end

app/views/first_information_reports/_form.html.erb
<%= form_with(model: first_information_report) do |form| %>
  <div class="form-group text-start p-3">
    <div class="row mb-3">
      <div class="col-md-6">
        <%= form.label :user_id, 'Reporting Officer' %>
        <%= select_tag 'first_information_report[user_id]',
                       options_from_collection_for_select(users, :id,
                                                          ->(ob) {"#{ob.firstname} #{ob.lastname} (#{ob.id})"}),
                       prompt: "Choose", class: 'form-control', autofocus: true %>
      </div>

      <div class="col-md-6">
        <%= form.label :complainant_id %>
        <%= select_tag 'first_information_report[complainant_id]',
                       options_from_collection_for_select(complainants, :id,
                                                          ->(ob) {"#{ob.firstname} #{ob.surname} (#{ob.id})"}),
                       prompt: "Choose", class: 'form-control' %>
      </div>
    </div>

    <div class="row mb-3 mx-1">
      <%= form.label :offense %>
      <%= form.text_area :offense, required: true, autocomplete: "text", class: "form-control" %>
    </div>

    <div class="row mb-3">
      <div class="col-md-6">
        <%= form.label :date, class: '' %>
        <%= form.datetime_local_field :date, required: true, class: 'form-control' %>
      </div>

      <div class="col-md-6">
        <%= form.label :location %>
        <%= form.text_field :location, required: true, autocomplete: "text", class: "form-control" %>
      </div>
    </div>

    <div class="row mb-3 mx-1">
      <%= form.label :suspect_details %>
      <%= form.text_area :suspect_details, required: true, autocomplete: "text", class: "form-control" %>
    </div>

    <div class="text-center my-4">
      <%= form.submit class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/first_information_reports/_nav_firs.html.erb
<div class="d-flex justify-content-between bg-white p-2 mb-2">
  <h4>Menu</h4>
  <nav>
    <%= link_to 'Add FIR', new_first_information_report_path, class: 'btn btn-success' %>
    <%= link_to 'All FIRs', first_information_reports_path, class: 'btn btn-info' %>
  </nav>
</div>

app/views/first_information_reports/edit.html.erb
<%= render './dashboard/sidebar' %>
<div class="main-content">
  <%= render './dashboard/header', title: 'FIR :: EDIT' %>
  <main>
    <%= render 'layouts/alerts' %>
    <%= render 'nav_firs' %>
    <%= render 'layouts/form_errors', obj: @first_information_report %>
    <div class="bg-white p-2 text-center">
      <h5 class="my-4">Editing First Information Report</h5>

      <%= render 'form', first_information_report: @first_information_report, users: @users, complainants: @complainants %>

      <%= link_to 'Show', @first_information_report %> |
      <%= link_to 'Back', first_information_reports_path %>
    </div>
  </main>
  <div class="text-center">
    <%= render 'layouts/footer' %>
  </div>
</div>

app/views/first_information_reports/index.html.erb
<%= render './dashboard/sidebar' %>
<div class="main-content">
  <%= render './dashboard/header', title: 'First Information Reports' %>
  <main>
    <%= render 'layouts/alerts' %>
    <%= render 'nav_firs' %>
    <div class="bg-white p-2 ">
      <table class="table">
        <thead>
        <tr>
          <th scope="col">UID</th>
          <th scope="col">Officer</th>
          <th scope="col">Complainant</th>
          <th scope="col">Offense</th>
          <th scope="col">Date</th>
          <th scope="col">Location</th>
          <th scope="col">Status</th>
          <th scope="col">Actions</th>
        </tr>
        </thead>
        <tbody>
          <% @firs.each do |fir| %>
            <tr>
              <td><%= id_formatter(fir.id) %></td>
              <td><%= "#{fir.user.firstname.titlecase } #{fir.user.lastname.titlecase }" %></td>
              <td>
                <%= link_to complainant_path(fir.complainant) do %>
                  <%= "#{fir.complainant.firstname.titlecase} #{fir.complainant.surname.titlecase }" %>
                  <p>(<%= fir.complainant.phone %>)</p>
                <% end %>
              </td>
              <td><%= fir.offense %></td>
              <td><%= fir.date.strftime('%D') %></td>
              <td><%= fir.location %></td>
              <td><%= fir.status %></td>
              <td>
                <%= link_to fir, class: 'badge bg-dark' do %>
                  <span class="las la-eye"></span>
                <% end %>
                <%= link_to edit_first_information_report_path(fir), class: 'badge bg-info' do %>
                  <span class="las la-user-edit"></span>
                <% end %>
                <% if current_user.admin? %>
                  <% if fir.pending? || fir.rejected? %>
                    <%= link_to approve_fir_path(fir), method: :post, class: 'badge bg-success', data: {confirm: 'Approve FIR?' } do %>
                      <span class="las la-check-square"></span>
                    <% end %>
                  <% end %>
                  <% if fir.approved? %>
                    <%= link_to reject_fir_path(fir), method: :post, class: 'badge bg-warning', data: {confirm: 'Reject FIR?' } do %>
                      <span class="">X</span>
                    <% end %>
                  <% end %>
                  <%= link_to first_information_report_path(fir), method: :delete, class: 'badge bg-danger', data: {confirm: 'Delete FIR?' } do %>
                    <span class="las la-trash"></span>
                  <% end %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= will_paginate @firs, renderer: BootstrapPagination::Rails %>
    </div>

  </main>
  <div class="text-center">
    <%= render 'layouts/footer' %>
  </div>
</div>

app/views/first_information_reports/new.html.erb
<%= render './dashboard/sidebar' %>
<div class="main-content">
  <%= render './dashboard/header', title: 'First Information Reports' %>
  <main>
    <%= render 'layouts/alerts' %>
    <%= render 'nav_firs' %>
    <%= render 'layouts/form_errors', obj: @first_information_report %>
    <div class="bg-white p-2 text-center">
      <h5 class="my-4">New First Information Report</h5>

      <%= render 'form', first_information_report: @first_information_report, users: @users, complainants: @complainants %>

      <%= link_to 'Show', @first_information_report %> |
      <%= link_to 'Back', first_information_reports_path %>
    </div>
  </main>
  <div class="text-center">
    <%= render 'layouts/footer' %>
  </div>
</div>

app/views/first_information_reports/show.html.erb
<%= render './dashboard/sidebar' %>
<div class="main-content">
  <%= render './dashboard/header', title: 'First Information Report' %>
  <main>
    <%= render 'layouts/alerts' %>
    <%= render 'nav_firs' %>
    <div class="bg-white p-2">
      <div class="card text-center">
        <h5 class="card-header p-3">FIR ID: <strong><%= @first_information_report.id %></strong> Details</h5>
        <span class="badge bg-<%= detect_status(@first_information_report.status) %>">
          <%= @first_information_report.status %>
        </span>
        <div class="card-body">
          <h5 class="card-title text-uppercase my-3"><strong class="d-block">Offense:</strong> <%= @first_information_report.offense %></h5>
          <p>
            <strong class="d-block text-capitalize">Reporting Officer: </strong>
            <%=
              "#{@first_information_report.user.firstname}
              #{@first_information_report.user.lastname}"
            %>
            <small>(<%= @first_information_report.user.admin ? 'Admin Officer' : 'Police Officer' %>)</small>
          </p>
          <p><strong  class="d-block">Suspect Details: </strong><%= @first_information_report.suspect_details %></p>
          <p>
            <strong  class="d-block">Complainant: </strong>
            <%=
              "#{@first_information_report.complainant.firstname}
              #{@first_information_report.complainant.surname}"
            %>
            <small>(<%= @first_information_report.complainant.phone %>)</small>
          </p>
          <p>
            <strong  class="d-block">Location: </strong>
            <%= @first_information_report.location %>
          </p>
          <p><strong  class="d-block">Date: </strong><%= @first_information_report.date.strftime('%c') %></p>
          <%= link_to 'Back', first_information_reports_path %>
        </div>
      </div>
    </div>
  </main>
  <div class="text-center">
    <%= render 'layouts/footer' %>
  </div>
</div>